pipeline {
    agent any
     environment {
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
        }
    stages {
        stage('Setup') {
            steps {
                sh "bash /home/azureuser/DnD-character-Gen/Jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash /home/azureuser/DnD-character-Gen/Jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                sh "bash /home/azureuser/DnD-character-Gen/Jenkins/build.sh"
            }
        }
        stage('Push') {
            steps {
                sh "bash /home/azureuser/DnD-character-Gen/Jenkins/push/sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash /home/azureuser/DnD-character-Gen/Jenkins/deploy.sh"
            }
        }
    }
    post {
        always {
            junit 'test_reports/*_junit_report.xml'
            cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'test_reports/*_coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
        }
    }
}